//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace App.WCSDataService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WCSDataServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WCSDataService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback transWCSExecuteTaskOperationCompleted;
        
        private System.Threading.SendOrPostCallback transWCSTaskStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WCSDataService() {
            this.Url = global::App.Properties.Settings.Default.App_WCSDataService_WCSDataService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event transWCSExecuteTaskCompletedEventHandler transWCSExecuteTaskCompleted;
        
        /// <remarks/>
        public event transWCSTaskStatusCompletedEventHandler transWCSTaskStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/transWCSExecuteTask", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string transWCSExecuteTask(string TaskNo) {
            object[] results = this.Invoke("transWCSExecuteTask", new object[] {
                        TaskNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void transWCSExecuteTaskAsync(string TaskNo) {
            this.transWCSExecuteTaskAsync(TaskNo, null);
        }
        
        /// <remarks/>
        public void transWCSExecuteTaskAsync(string TaskNo, object userState) {
            if ((this.transWCSExecuteTaskOperationCompleted == null)) {
                this.transWCSExecuteTaskOperationCompleted = new System.Threading.SendOrPostCallback(this.OntransWCSExecuteTaskOperationCompleted);
            }
            this.InvokeAsync("transWCSExecuteTask", new object[] {
                        TaskNo}, this.transWCSExecuteTaskOperationCompleted, userState);
        }
        
        private void OntransWCSExecuteTaskOperationCompleted(object arg) {
            if ((this.transWCSExecuteTaskCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.transWCSExecuteTaskCompleted(this, new transWCSExecuteTaskCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/transWCSTaskStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string transWCSTaskStatus(string TaskNo) {
            object[] results = this.Invoke("transWCSTaskStatus", new object[] {
                        TaskNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void transWCSTaskStatusAsync(string TaskNo) {
            this.transWCSTaskStatusAsync(TaskNo, null);
        }
        
        /// <remarks/>
        public void transWCSTaskStatusAsync(string TaskNo, object userState) {
            if ((this.transWCSTaskStatusOperationCompleted == null)) {
                this.transWCSTaskStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OntransWCSTaskStatusOperationCompleted);
            }
            this.InvokeAsync("transWCSTaskStatus", new object[] {
                        TaskNo}, this.transWCSTaskStatusOperationCompleted, userState);
        }
        
        private void OntransWCSTaskStatusOperationCompleted(object arg) {
            if ((this.transWCSTaskStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.transWCSTaskStatusCompleted(this, new transWCSTaskStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void transWCSExecuteTaskCompletedEventHandler(object sender, transWCSExecuteTaskCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class transWCSExecuteTaskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal transWCSExecuteTaskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void transWCSTaskStatusCompletedEventHandler(object sender, transWCSTaskStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class transWCSTaskStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal transWCSTaskStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591